

package kazieurope;
import java.sql.Connection;
    import java.sql.DriverManager;
    import java.sql.PreparedStatement;
    import java.sql.SQLException;
    import java.sql.Statement;
    import java.sql.ResultSet;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author jarekstarke
 */
public class NewJFrameAdmin extends javax.swing.JFrame {

   Connection con;
    //Statement st;
 
   // ResultSet rs;

    public NewJFrameAdmin() {
        initComponents();
   jInternalFrameWorkers.setVisible(false);
   
        String url="jdbc:mysql://mariadb105.server004689.nazwa.pl/server004689_kazieurope";
        String user="server004689_kazieurope";
        String pass=" ";
        
        try {
            con =DriverManager.getConnection(url,user,pass);
        }catch (SQLException ex) {
            System.out.println("error :"+ ex.getMessage());
        } 
    
    
    
    
    
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jInternalFrameWorkers = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmployees = new javax.swing.JTable();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HR Administration panel");
        setBackground(new java.awt.Color(87, 155, 238));
        setBounds(new java.awt.Rectangle(250, 250, 0, 0));
        setMinimumSize(new java.awt.Dimension(100, 100));

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel1.setText("Select the module with which you want to work in the upper menu");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jInternalFrameWorkers.setBorder(null);
        jInternalFrameWorkers.setClosable(true);
        jInternalFrameWorkers.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jInternalFrameWorkers.setVisible(true);
        jInternalFrameWorkers.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jInternalFrameWorkersComponentHidden(evt);
            }
        });

        jScrollPane1.setBorder(null);

        jTableEmployees.setAutoCreateRowSorter(true);
        jTableEmployees.setBackground(java.awt.SystemColor.window);
        jTableEmployees.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTableEmployees.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTableEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Firstname", "Lastname", "Email", "Phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEmployees.setOpaque(false);
        jTableEmployees.setSelectionBackground(new java.awt.Color(102, 153, 255));
        jTableEmployees.setSelectionForeground(java.awt.SystemColor.window);
        jTableEmployees.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableEmployees.setShowGrid(true);
        jTableEmployees.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTableEmployeesAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTableEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEmployeesMouseClicked(evt);
            }
        });
        jTableEmployees.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableEmployeesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEmployees);
        jTableEmployees.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTableEmployees.getColumnModel().getColumnCount() > 0) {
            jTableEmployees.getColumnModel().getColumn(0).setPreferredWidth(15);
            jTableEmployees.getColumnModel().getColumn(1).setPreferredWidth(15);
            jTableEmployees.getColumnModel().getColumn(2).setResizable(false);
            jTableEmployees.getColumnModel().getColumn(2).setPreferredWidth(60);
        }

        javax.swing.GroupLayout jInternalFrameWorkersLayout = new javax.swing.GroupLayout(jInternalFrameWorkers.getContentPane());
        jInternalFrameWorkers.getContentPane().setLayout(jInternalFrameWorkersLayout);
        jInternalFrameWorkersLayout.setHorizontalGroup(
            jInternalFrameWorkersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameWorkersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jInternalFrameWorkersLayout.setVerticalGroup(
            jInternalFrameWorkersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameWorkersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        jMenu4.setText("Recruitment");
        jMenu4.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jMenuItem3.setText("Managing existing job offers");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jMenuItem4.setText("Creating job offers");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem7.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jMenuItem7.setText("Administration with answers on job offers");
        jMenuItem7.setActionCommand("");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuBar2.add(jMenu4);

        jMenu5.setText("Employees");
        jMenu5.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem5.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jMenuItem5.setText("Settlement of employee working time");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem9.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jMenuItem9.setText("Payments of the monthly salary");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem6.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jMenuItem6.setText("Personal data management");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuBar2.add(jMenu5);

        jMenu6.setText("Settlement with companies");
        jMenu6.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jMenuItem1.setText("Creating monthly settlements with partners - for the work of employees.");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem1);

        jMenuItem8.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jMenuItem8.setText("Settlement of invoices issued to partners.");
        jMenu6.add(jMenuItem8);

        jMenuItem2.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jMenuItem2.setText("A database contained with partners of cooperation agreements.");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem2);

        jMenuItem10.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jMenuItem10.setText("Creating offers for workplaces from the database of people interested in work.");
        jMenuItem10.setActionCommand("Creating offers for workplaces from the database of people interested in work.");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem10);

        jMenuBar2.add(jMenu6);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(326, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
            .addComponent(jInternalFrameWorkers)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jInternalFrameWorkers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        jLabel1.setText("Employees data managament");
      jInternalFrameWorkers.setVisible(true);
     //NewJFrameWorker.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
        //new NewJFrameAdmin().setVisible(true);
        jLabel1.setText("Invoices partner");
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        jLabel1.setText("Salary module");
        
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        jLabel1.setText("Settlement of working time");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jTableEmployeesAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTableEmployeesAncestorAdded
      
        
//        DefaultTableModel model =  (DefaultTableModel)JTableEmployees.getModel();  
        
       String sql = "SELECT userfirstname,userlastname,email,phone  FROM users LIMIT 100";
       
       try {
          
            PreparedStatement st = con.prepareStatement(sql);
            ResultSet rs = st.executeQuery(sql);
            
            while (rs.next())
            {
                String Firstname = rs.getString("userfirstname");
                String Lastname = rs.getString("userlastname");
                String Mail =   rs.getString("email");
                String Phone =    rs.getString("phone");
                
                 Object[] row = {Firstname,Lastname,Mail,Phone};

    DefaultTableModel model = (DefaultTableModel) jTableEmployees.getModel();

    model.addRow(row);

        } 
                            
            
            
            System.out.println(rs);
            
        }catch (Exception ex) {
            System.out.println("error :"+ ex.getMessage());
        } 
    }//GEN-LAST:event_jTableEmployeesAncestorAdded

    private void jInternalFrameWorkersComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jInternalFrameWorkersComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jInternalFrameWorkersComponentHidden

    private void jTableEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEmployeesMouseClicked
        
         int row = jTableEmployees.rowAtPoint(evt.getPoint());
         
         if (row >= 0 ) {
                        new NewJFrameWorker().setVisible(true);

                        }
         
    }//GEN-LAST:event_jTableEmployeesMouseClicked

    private void jTableEmployeesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableEmployeesKeyPressed
        // TODO add your handling code here:
        
      /*  
        int row = jTableEmployees.rowAtPoint(evt.getPoint());
         
         if (row >= 0 ) {
                        new NewJFrameWorker().setVisible(true);

                        }   */
        
        
        
        
    }//GEN-LAST:event_jTableEmployeesKeyPressed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrameAdmin().setVisible(true);
            
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrameWorkers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmployees;
    // End of variables declaration//GEN-END:variables
}
